# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app.kubernetes.io/component: exporter
#     app.kubernetes.io/name: kube-state-metrics
#     app.kubernetes.io/version: 2.15.0
#   name: kube-state-metrics-cluster
#   namespace: kube-system
# spec:
#   clusterIP: None
#   ports:
#   - name: http-metrics
#     port: 8082
#     targetPort: http-metrics
#   - name: telemetry
#     port: 8081
#     targetPort: telemetry
#   selector:
#     app.kubernetes.io/name: kube-state-metrics
# ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.15.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  ports:
    - port: 8082
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: kube-state-metrics
  type: LoadBalancer