stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

include:
  - template: 'Terraform/Base.gitlab-ci.yml'

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends: .terraform:build
  environment:
    name: $TF_STATE_NAME
    action: prepare
  before_script:
    - mkdir .ssh
    - echo $CI_KEY_SSH > .ssh/id_rsa.pub
    - echo "{ name = \"truc\"" > terraform.tfvars
    - echo " password = \"azerty\"}" >> terraform.tfvars
    - cat terraform.tfvars
    - echo $CI_TERRAFORM_USER
  script:
    - ""
#    - gitlab-terraform plan -var 'user=$CI_TERRAFORM_USER' -var 'ssh_user=$CI_USER_SSH'
#    - gitlab-terraform plan-json

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
    action: start