global:
  scrape_interval: 15s  # Intervalle pour scrapper les données

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Cible Prometheus lui-même

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Cible Grafana (sur le même réseau)