- name: Déploiement de Grafana et Prometheus avec Docker
  hosts: all
  become: true
  tasks:

    # Étape 1 : Mise à jour et installation des paquets nécessaires
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes
        upgrade: yes

    - name: Installer les dépendances
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-pip
        state: present

    # Étape 2 : Vérifier et formater le disque persistant s'il n'est pas encore formaté
    - name: Vérifier si le disque est monté
      shell: lsblk | grep monitoring-data-disk
      register: disk_check
      ignore_errors: true

    - name: Formater le disque si nécessaire
      shell: mkfs.ext4 /dev/disk/by-id/google-monitoring-data-disk
      when: disk_check.rc != 0

    - name: Créer le répertoire de stockage
      file:
        path: /mnt/monitoring-data
        state: directory
        mode: '0755'

    - name: Monter le disque
      mount:
        path: /mnt/monitoring-data
        src: /dev/disk/by-id/google-monitoring-data-disk
        fstype: ext4
        opts: defaults
        state: mounted

    - name: Ajouter le disque au fichier /etc/fstab pour montage automatique au démarrage
      lineinfile:
        path: /etc/fstab
        line: "/dev/disk/by-id/google-monitoring-data-disk /mnt/monitoring-data ext4 defaults 0 2"
        state: present

    # Étape 3 : Activer et configurer Docker
    - name: Activer et démarrer Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Ajouter l'utilisateur actuel au groupe Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Étape 4 : Préparer les fichiers de monitoring
    - name: Créer un répertoire pour les fichiers de monitoring
      file:
        path: /home/{{ ansible_user }}/monitoring
        state: directory
        mode: '0755'

    - name: Copier le fichier docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /home/{{ ansible_user }}/monitoring/docker-compose.yml
        mode: '0644'

    - name: Copier le fichier de configuration Prometheus
      copy:
        src: ./prometheus.yml
        dest: /home/{{ ansible_user }}/monitoring/prometheus.yml
        mode: '0644'

    - name: Copier le fichier des règles d'alerte pour Prometheus
      copy:
        src: ./alert_rules.yml
        dest: /home/{{ ansible_user }}/monitoring/alert_rules.yml
        mode: '0644'

    - name: Copier le fichier de configuration d'Alertmanager
      copy:
        src: ./alertmanager.yml
        dest: /home/{{ ansible_user }}/monitoring/alertmanager.yml
        mode: '0644'

    # Étape 5 : Démarrer les services avec Docker Compose en utilisant le disque persistant
    - name: Démarrer les services avec Docker Compose
      command:
        chdir: /home/{{ ansible_user }}/monitoring
        cmd: docker-compose up -d