# Étape 4 :  Préparer les fichiers de monitoring
- name: Créer un répertoire pour les fichiers de monitoring
  file:
    path: /home/{{ ansible_user }}/monitoring
    state: directory
    mode: '0755'

- name: Copier le fichier docker-compose.yml
  copy:
    src: ./files/docker-compose.yml
    dest: /home/{{ ansible_user }}/monitoring/docker-compose.yml
    mode: '0644'

- name: Copier le fichier de configuration Prometheus
  copy:
    src: ./files/prometheus.yml
    dest: /home/{{ ansible_user }}/monitoring/prometheus.yml
    mode: '0644'

- name: Copier le fichier des règles d'alerte pour Prometheus
  copy:
    src: ./files/alert_rules.yml
    dest: /home/{{ ansible_user }}/monitoring/alert_rules.yml
    mode: '0644'

- name: Copier le fichier de configuration d'Alertmanager
  copy:
    src: ./files/alertmanager.yml
    dest: /home/{{ ansible_user }}/monitoring/alertmanager.yml
    mode: '0644'

- name: Démarrer les services avec Docker Compose
  command:
    chdir: /home/{{ ansible_user }}/monitoring
    cmd: docker-compose up -d