---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Créer le fichier de configuration Nginx pour le reverse proxy
  template:
    src: nocodb.conf.j2
    dest: /etc/nginx/sites-available/nocodb
  notify:
    - restart nginx

- name: Créer un lien symbolique vers sites-enabled
  file:
    src: /etc/nginx/sites-available/nocodb
    dest: /etc/nginx/sites-enabled/nocodb
    state: link

- name: Vérifier la configuration Nginx
  command: nginx -t
  notify:
    - restart nginx

- name: Redémarrer Nginx
  service:
    name: nginx
    state: restarted
